# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

log_sgt0 <- function(x, sigma, skew, p, q, mean_cent, var_adj) {
    .Call(`_rbsvar_log_sgt0`, x, sigma, skew, p, q, mean_cent, var_adj)
}

log_sgt0_vec <- function(x, sigma, skew, log_p, log_q, mean_cent, var_adj) {
    .Call(`_rbsvar_log_sgt0_vec`, x, sigma, skew, log_p, log_q, mean_cent, var_adj)
}

p_sgt0 <- function(x, sigma, skew, p, q, mean_cent, var_adj) {
    .Call(`_rbsvar_p_sgt0`, x, sigma, skew, p, q, mean_cent, var_adj)
}

abse_sgt0 <- function(sigma, skew, p, q, mean_cent, var_adj, resolution = 10L) {
    .Call(`_rbsvar_abse_sgt0`, sigma, skew, p, q, mean_cent, var_adj, resolution)
}

dmvnrm_arma <- function(x, mean, sigma, logd = TRUE) {
    .Call(`_rbsvar_dmvnrm_arma`, x, mean, sigma, logd)
}

dmvnrm_arma_diagonal <- function(x, mean, sds, logd = TRUE) {
    .Call(`_rbsvar_dmvnrm_arma_diagonal`, x, mean, sds, logd)
}

fill_xx <- function(xx, yy, m, t) {
    .Call(`_rbsvar_fill_xx`, xx, yy, m, t)
}

log_like <- function(state, yy, xx, first_b, first_sgt, first_garch, first_regime, first_yna, m, A_rows, t, regimes, yna_indices, B_inverse, mean_cent, var_adj, parallel_likelihood) {
    .Call(`_rbsvar_log_like`, state, yy, xx, first_b, first_sgt, first_garch, first_regime, first_yna, m, A_rows, t, regimes, yna_indices, B_inverse, mean_cent, var_adj, parallel_likelihood)
}

check_permutation <- function(B) {
    .Call(`_rbsvar_check_permutation`, B)
}

log_dirichlet <- function(x, alpha = 2) {
    .Call(`_rbsvar_log_dirichlet`, x, alpha)
}

log_prior <- function(state, yy, xx, first_b, first_sgt, first_garch, first_regime, first_yna, m, A_rows, t, regimes, a_mean, a_cov, prior_A_diagonal, b_mean, b_cov, p_prior_mode, p_prior_scale, q_prior_mode, q_prior_scale, dirichlet_alpha, B_inverse) {
    .Call(`_rbsvar_log_prior`, state, yy, xx, first_b, first_sgt, first_garch, first_regime, first_yna, m, A_rows, t, regimes, a_mean, a_cov, prior_A_diagonal, b_mean, b_cov, p_prior_mode, p_prior_scale, q_prior_mode, q_prior_scale, dirichlet_alpha, B_inverse)
}

sampler <- function(N, n, m0, K, gamma, init_draws, output_as_input, old_chain, new_chain, parallel, parallel_likelihood, model_R, progress_bar) {
    .Call(`_rbsvar_sampler`, N, n, m0, K, gamma, init_draws, output_as_input, old_chain, new_chain, parallel, parallel_likelihood, model_R, progress_bar)
}

stackA_cpp <- function(A, constant = TRUE) {
    .Call(`_rbsvar_stackA_cpp`, A, constant)
}

irf_cpp <- function(s, horizon, cumulate, shock_sizes, shocks, A_rows, first_b, first_sgt, m, B_inverse, parallel) {
    .Call(`_rbsvar_irf_cpp`, s, horizon, cumulate, shock_sizes, shocks, A_rows, first_b, first_sgt, m, B_inverse, parallel)
}

log_text <- function(text, iter) {
    invisible(.Call(`_rbsvar_log_text`, text, iter))
}

logSumExp <- function(x) {
    .Call(`_rbsvar_logSumExp`, x)
}

log_ml_cpp <- function(proposal_densities, posterior_densities, theta_star, sigma_star, logden_star, J, parallel, parallel_likelihood, model_R) {
    .Call(`_rbsvar_log_ml_cpp`, proposal_densities, posterior_densities, theta_star, sigma_star, logden_star, J, parallel, parallel_likelihood, model_R)
}

