# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

log_sgt0 <- function(x, sigma, skew, p, q, mean_cent, var_adj) {
    .Call(`_rbsvar_log_sgt0`, x, sigma, skew, p, q, mean_cent, var_adj)
}

dmvnrm_arma <- function(x, mean, sigma, logd = TRUE) {
    .Call(`_rbsvar_dmvnrm_arma`, x, mean, sigma, logd)
}

dmvnrm_arma_diagonal <- function(x, mean, sds, logd = TRUE) {
    .Call(`_rbsvar_dmvnrm_arma_diagonal`, x, mean, sds, logd)
}

fill_xx <- function(xx, yy, m, t) {
    .Call(`_rbsvar_fill_xx`, xx, yy, m, t)
}

garch_out <- function(yy, fit, B, GARCH, t, m) {
    .Call(`_rbsvar_garch_out`, yy, fit, B, GARCH, t, m)
}

log_like <- function(state, yy, xx, first_b, first_sgt, first_garch, first_yna, m, A_rows, t, yna_indices, B_inverse, mean_cent, var_adj, parallel_likelihood) {
    .Call(`_rbsvar_log_like`, state, yy, xx, first_b, first_sgt, first_garch, first_yna, m, A_rows, t, yna_indices, B_inverse, mean_cent, var_adj, parallel_likelihood)
}

check_permutation <- function(B) {
    .Call(`_rbsvar_check_permutation`, B)
}

log_prior <- function(state, yy, xx, first_b, first_sgt, first_garch, first_yna, m, A_rows, t, a_mean, a_cov, prior_A_diagonal, b_mean, b_cov, p_prior_mode, p_prior_scale, q_prior_mode, q_prior_scale, r_prior_mode, r_prior_scale, B_inverse) {
    .Call(`_rbsvar_log_prior`, state, yy, xx, first_b, first_sgt, first_garch, first_yna, m, A_rows, t, a_mean, a_cov, prior_A_diagonal, b_mean, b_cov, p_prior_mode, p_prior_scale, q_prior_mode, q_prior_scale, r_prior_mode, r_prior_scale, B_inverse)
}

draw <- function(draws, densities, asums, state_row, last_row, gamma, K, n, yy, xx, first_b, first_sgt, first_garch, first_yna, m, A_rows, t, yna_indices, B_inverse, a_mean, a_cov, prior_A_diagonal, b_mean, b_cov, p_prior_mode, p_prior_scale, q_prior_mode, q_prior_scale, r_prior_mode, r_prior_scale, mean_cent, var_adj, parallel_likelihood) {
    invisible(.Call(`_rbsvar_draw`, draws, densities, asums, state_row, last_row, gamma, K, n, yy, xx, first_b, first_sgt, first_garch, first_yna, m, A_rows, t, yna_indices, B_inverse, a_mean, a_cov, prior_A_diagonal, b_mean, b_cov, p_prior_mode, p_prior_scale, q_prior_mode, q_prior_scale, r_prior_mode, r_prior_scale, mean_cent, var_adj, parallel_likelihood))
}

sampler <- function(N, n, m0, K, gamma, init_draws, output_as_input, old_chain, new_chain, parallel, parallel_likelihood, yy, xx, m, A_rows, t, yna_indices, B_inverse, mean_cent, var_adj, first_b, first_sgt, first_garch, first_yna, a_mean, a_cov, prior_A_diagonal, b_mean, b_cov, p_prior_mode, p_prior_scale, q_prior_mode, q_prior_scale, r_prior_mode, r_prior_scale, progress_bar) {
    .Call(`_rbsvar_sampler`, N, n, m0, K, gamma, init_draws, output_as_input, old_chain, new_chain, parallel, parallel_likelihood, yy, xx, m, A_rows, t, yna_indices, B_inverse, mean_cent, var_adj, first_b, first_sgt, first_garch, first_yna, a_mean, a_cov, prior_A_diagonal, b_mean, b_cov, p_prior_mode, p_prior_scale, q_prior_mode, q_prior_scale, r_prior_mode, r_prior_scale, progress_bar)
}

stackA_cpp <- function(A, constant = TRUE) {
    .Call(`_rbsvar_stackA_cpp`, A, constant)
}

irf_cpp <- function(s, horizon, cumulate, shock_sizes, shocks, A_rows, first_b, first_sgt, m, B_inverse, parallel) {
    .Call(`_rbsvar_irf_cpp`, s, horizon, cumulate, shock_sizes, shocks, A_rows, first_b, first_sgt, m, B_inverse, parallel)
}

log_text <- function(text, iter) {
    invisible(.Call(`_rbsvar_log_text`, text, iter))
}

logSumExp <- function(x) {
    .Call(`_rbsvar_logSumExp`, x)
}

log_ml_cpp <- function(proposal_densities, posterior_densities, theta_star, sigma_star, logden_star, J, yy, xx, m, A_rows, t, yna_indices, B_inverse, mean_cent, var_adj, first_b, first_sgt, first_garch, first_yna, a_mean, a_cov, prior_A_diagonal, b_mean, b_cov, p_prior_mode, p_prior_scale, q_prior_mode, q_prior_scale, r_prior_mode, r_prior_scale, parallel = FALSE, parallel_likelihood = FALSE) {
    .Call(`_rbsvar_log_ml_cpp`, proposal_densities, posterior_densities, theta_star, sigma_star, logden_star, J, yy, xx, m, A_rows, t, yna_indices, B_inverse, mean_cent, var_adj, first_b, first_sgt, first_garch, first_yna, a_mean, a_cov, prior_A_diagonal, b_mean, b_cov, p_prior_mode, p_prior_scale, q_prior_mode, q_prior_scale, r_prior_mode, r_prior_scale, parallel, parallel_likelihood)
}

