# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

log_sgt0 <- function(x, sigma, skew, p, q, mean_cent, var_adj) {
    .Call(`_rbsvar_log_sgt0`, x, sigma, skew, p, q, mean_cent, var_adj)
}

log_like <- function(state, yy, xx, first_b, first_sgt, m, A_rows, t, mean_cent, var_adj, parallel_likelihood) {
    .Call(`_rbsvar_log_like`, state, yy, xx, first_b, first_sgt, m, A_rows, t, mean_cent, var_adj, parallel_likelihood)
}

log_prior <- function(state, yy, xx, first_b, first_sgt, m, A_rows, t, p_prior_mode, p_prior_scale, q_prior_mode, q_prior_scale, shrinkage) {
    .Call(`_rbsvar_log_prior`, state, yy, xx, first_b, first_sgt, m, A_rows, t, p_prior_mode, p_prior_scale, q_prior_mode, q_prior_scale, shrinkage)
}

draw <- function(draws, densities, asums, state_row, last_row, gamma, K, n, yy, xx, first_b, first_sgt, m, A_rows, t, mean_cent, var_adj, p_prior_mode, p_prior_scale, q_prior_mode, q_prior_scale, shrinkage, parallel_likelihood) {
    invisible(.Call(`_rbsvar_draw`, draws, densities, asums, state_row, last_row, gamma, K, n, yy, xx, first_b, first_sgt, m, A_rows, t, mean_cent, var_adj, p_prior_mode, p_prior_scale, q_prior_mode, q_prior_scale, shrinkage, parallel_likelihood))
}

sampler <- function(N, n, m0, K, gamma, init_mode, init_scale, output_as_input, old_chain, new_chain, parallel, parallel_likelihood, yy, xx, m, A_rows, t, mean_cent, var_adj, first_b, first_sgt, p_prior_mode, p_prior_scale, q_prior_mode, q_prior_scale, shrinkage, progress_bar) {
    .Call(`_rbsvar_sampler`, N, n, m0, K, gamma, init_mode, init_scale, output_as_input, old_chain, new_chain, parallel, parallel_likelihood, yy, xx, m, A_rows, t, mean_cent, var_adj, first_b, first_sgt, p_prior_mode, p_prior_scale, q_prior_mode, q_prior_scale, shrinkage, progress_bar)
}

test <- function() {
    invisible(.Call(`_rbsvar_test`))
}

